apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://hospital-database:5432/hospitaldb
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_USERNAME: hospital
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_H2_CONSOLE_ENABLED: "false"
  SERVER_PORT: "8080"
  APP_CORS_ALLOWED_ORIGINS: http://hospital-frontend
  APP_PASSWORD_RESET_EXPIRATION_MS: "3600000"
