apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-database
  template:
    metadata:
      labels:
        app: hospital-database
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: hospitaldb
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: hospital-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hospital-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
